### ISSUE TITLE
Critical error: (siad v1.5.7, Release: standard) explorer update failed: entry does not exist

### ISSUE THREAD

**Issue by berlincount** [SiaFoundation/siad#43]
```
Critical error: (siad v1.5.7, Release: standard) explorer update failed: entry does not exist
Please submit a bug report here: https://github.com/SiaFoundation/siad/issues
goroutine 1 [running]:
runtime/debug.Stack(0xac, 0xc0001642c0, 0xac)
        runtime/debug/stack.go:24 +0x9f
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x25
go.sia.tech/siad/build.Critical(0xc0002a76f8, 0x2, 0x2)
        go.sia.tech/siad/build/critical.go:20 +0x15e
go.sia.tech/siad/modules/explorer.(*Explorer).ProcessConsensusChange(0xc0003387e0, 0x822e8116aeb8d0d9, 0x20ca9e3f618e6f57, 0x6f7db611bc9d00e, 0xdb6186a9f0feec36, 0x51308, 0x0, 0x0, 0x0, 0xc0001b8720, ...)
        go.sia.tech/siad/modules/explorer/update.go:275 +0xe9
go.sia.tech/siad/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc00017a540, 0x0, 0xc00017a540)
        go.sia.tech/siad/modules/consensus/subscribe.go:212 +0x315
gitlab.com/NebulousLabs/bolt.(*DB).View(0xc0000daa00, 0xc0002a7d98, 0x0, 0x0)
        gitlab.com/NebulousLabs/bolt@v1.4.4/db.go:730 +0x93
go.sia.tech/siad/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc000117b80, 0xf6fd60, 0xc0003387e0, 0xfd8a21273b5a1e04, 0x9c5322f9d2efc661, 0x74de65cc202e44aa, 0x5fa67de6d0c77a03, 0x0, 0x0, 0x0, ...)
        go.sia.tech/siad/modules/consensus/subscribe.go:200 +0x325
go.sia.tech/siad/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc000117b80, 0xf6fd60, 0xc0003387e0, 0xfd8a21273b5a1e04, 0x9c5322f9d2efc661, 0x74de65cc202e44aa, 0x5fa67de6d0c77a03, 0x0, 0x0, 0x0)
        go.sia.tech/siad/modules/consensus/subscribe.go:256 +0x10a
go.sia.tech/siad/modules/explorer.New(0xf8db38, 0xc000117b80, 0xc0003826d8, 0x12, 0x12, 0xc0000999f0, 0xc0000da600)
        go.sia.tech/siad/modules/explorer/explorer.go:80 +0x1c7
go.sia.tech/siad/node.New.func3(0xc0002a8690, 0xf8db38, 0xc000117b80, 0xc0000b3cf0, 0x9, 0xc0002a8490, 0x8, 0xf8db38, 0xc000117b80, 0xc0001b83c0, ...)
        go.sia.tech/siad/node/node.go:328 +0x10b
go.sia.tech/siad/node.New(0x101010101010101, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        go.sia.tech/siad/node/node.go:335 +0xd33
go.sia.tech/siad/node/api/server.NewAsync.func1(0xe1d06f, 0xe, 0xc00010ae80, 0xe14c8e, 0x9, 0xc0000b4810, 0x20, 0xc04df6e9656c5e91, 0x1aa519, 0x149a800, ...)
        go.sia.tech/siad/node/api/server/server.go:219 +0x4b4
go.sia.tech/siad/node/api/server.NewAsync(0xe1d06f, 0xe, 0xe14c8e, 0x9, 0xc0000b4810, 0x20, 0x101010101010101, 0x1, 0x0, 0x0, ...)
        go.sia.tech/siad/node/api/server/server.go:241 +0x15c
go.sia.tech/siad/node/api/server.New(0xe1d06f, 0xe, 0xe14c8e, 0x9, 0xc0000b4810, 0x20, 0x101010101010101, 0x1, 0x0, 0x0, ...)
        go.sia.tech/siad/node/api/server/server.go:259 +0xe8
main.startDaemon(0xc0000b4810, 0x20, 0xe1d06f, 0xe, 0xe0bfbd, 0x5, 0xe0bfc2, 0x5, 0xe0bfc7, 0x5, ...)
        go.sia.tech/siad/cmd/siad/daemon.go:223 +0x2e8
main.startDaemonCmd(0xc000116840, 0xc0000c8640, 0x0, 0x2)
        go.sia.tech/siad/cmd/siad/daemon.go:289 +0x2f8
github.com/spf13/cobra.(*Command).execute(0xc000116840, 0xc00009a160, 0x2, 0x2, 0xc000116840, 0xc00009a160)
        github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000116840, 0xd, 0x0, 0x0)
        github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        go.sia.tech/siad/cmd/siad/main.go:213 +0x850
Critical error: (siad v1.5.7, Release: standard) explorer update failed: entry does not exist
Please submit a bug report here: https://github.com/SiaFoundation/siad/issues
```

no idea how to reproduce without my instance data, but happy to help debug.

**Comment by n8maninger** [comment]
The explorer module hasn't been maintained for a few years now and isn't run by default. Is there a reason you need to run it?

**Comment by berlincount** [comment]
nah. I think I activated it during installation out of curiosity. seems like I could/should just disable it, if only to get rid of the error.
